"""Config models, loading, and hashing.

Two hashes, not one (PRD §15 specifies one):

``extraction_hash`` covers only the stages that determine the contents of a
feature table -- data selection, signal processing, windowing, features. It is
stamped into every derived table (R19).

``full_hash`` additionally covers splits and training, and identifies a run.

The split matters because a cache miss now costs bandwidth, not just CPU
(R15/R19). Changing ``training.models`` must not invalidate 45.76 GB of
extraction work.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import Literal

import yaml
from pydantic import BaseModel, ConfigDict, Field, field_validator


class _Base(BaseModel):
    model_config = ConfigDict(extra="forbid", frozen=True)


class DataCfg(_Base):
    root: Path = Path("./data/chbmit")
    source: Literal["chbmit_raw", "csv_scaled"] = "chbmit_raw"
    csv_path: Path | None = None
    cases: list[str] | Literal["all"] = "all"
    on_missing_channel: Literal["skip_file", "fill_nan"] = "skip_file"
    dedupe: bool = True  # R6: never optional in practice; exposed only so the
    #                      leakage contrast run (R25) can be generated by code.


class SignalCfg(_Base):
    sample_rate: int = 256
    notch_hz: list[float] = Field(default_factory=lambda: [60.0, 120.0])
    bandpass: tuple[float, float] = (0.5, 80.0)
    # R16/R30: populated by the header pre-pass, applied as a downstream
    # projection. Empty means "keep every allowlisted channel".
    canonical_channels: list[str] = Field(default_factory=list)

    @field_validator("notch_hz")
    @classmethod
    def _notch_required(cls, v: list[float]) -> list[float]:
        # R21: the notch is not optional, on either dataset.
        if not v:
            raise ValueError("R21: notch_hz must not be empty; 60 Hz is mandatory")
        return v


class WindowCfg(_Base):
    length_sec: float = 10.0
    stride_sec: float = 10.0
    min_overlap_frac: float = 0.5
    guard_sec: float = 30.0


class FeatureCfg(_Base):
    bands: dict[str, tuple[float, float]] = Field(
        default_factory=lambda: {
            "delta": (0.5, 4.0),
            "theta": (4.0, 8.0),
            "alpha": (8.0, 13.0),
            "beta": (13.0, 30.0),
            "gamma": (30.0, 80.0),
        }
    )
    welch_nperseg: int = 512
    welch_noverlap: int = 256
    views: list[Literal["per_channel", "aggregated"]] = Field(
        default_factory=lambda: ["per_channel", "aggregated"]
    )


class SplitCfg(_Base):
    protocol: Literal["loso", "random_window", "grouped_pseudo"] = "loso"
    n_val_subjects: int = 4
    seed: int = 42


class TrainCfg(_Base):
    models: list[Literal["dummy", "logreg", "rf", "hgb"]] = Field(
        default_factory=lambda: ["dummy", "logreg", "rf", "hgb"]
    )
    negative_downsample_ratio: int | None = 10
    threshold_metric: Literal["f2", "f1"] = "f2"
    consecutive_k: list[int] = Field(default_factory=lambda: [1, 2, 3])
    # PRD 9.3 inner loop. Off by default because it multiplies fits by
    # |grid| x inner_splits inside every one of 23 outer folds.
    search: bool = False
    inner_splits: int = 3
    # Choose (threshold, k) together rather than threshold-then-k. The two
    # interact: a high threshold admits few windows, which cannot form a long
    # run, so a sequential choice can select a pair that detects nothing.
    joint_threshold_k: bool = False
    joint_grid: int = 24
    # An owner-designated headline model. Left None, the report picks by mean
    # validation F2 (R36). Set, it overrides that choice -- and the report must
    # say so, because a configuration chosen with knowledge of the test results
    # carries selection bias that an automatically selected one does not.
    headline_model: Literal["dummy", "logreg", "rf", "hgb"] | None = None
    # PRD 8.2: absolute EEG amplitude tracks skull thickness, electrode
    # impedance, age and amplifier gain, so it is close to a subject
    # fingerprint. Restricting to amplitude-invariant columns tests whether the
    # cross-subject leak rides on scale. This lives in `training`, not
    # `features`, on purpose: it is a column filter applied after extraction,
    # so it must not perturb extraction_hash and orphan the feature store.
    feature_subset: Literal["all", "amplitude_invariant", "amplitude_dependent"] = "all"
    # What the headline model is selected on. "window_f2" is the historical
    # behaviour and cannot see the seizures-versus-false-alarms trade, which is
    # why it disagreed with an event-level judgement and forced an owner
    # override. "event_f2" scores validation subjects at the event level, so the
    # same preference can be expressed without ever consulting a test metric.
    select_on: Literal["window_f2", "event_f2"] = "window_f2"
    # Re-derive the ictal label from the stored `overlap_frac` column at
    # training time. PRD 6.2's knob is `windowing.min_overlap_frac`, but that
    # field feeds `extraction_hash`: changing it orphans the 697 MB feature
    # store, and since ingest deletes raw files after extraction (R11/R14),
    # rebuilding would mean re-downloading 45.76 GB. `overlap_frac` is kept on
    # every window precisely so the same decision can be made as a column
    # operation instead. It therefore lives in `training`, which only moves
    # `full_hash`. None = use the label as extracted.
    relabel_overlap_min: float | None = None


class TrackCfg(_Base):
    mlflow_experiment: str | None = None
    local_artifacts: Path = Path("./artifacts")


class Config(_Base):
    data: DataCfg = DataCfg()
    signal: SignalCfg = SignalCfg()
    windowing: WindowCfg = WindowCfg()
    features: FeatureCfg = FeatureCfg()
    splits: SplitCfg = SplitCfg()
    training: TrainCfg = TrainCfg()
    tracking: TrackCfg = TrackCfg()

    # -- hashing ---------------------------------------------------------
    def _stable(self, keys: tuple[str, ...]) -> str:
        blob = {k: json.loads(getattr(self, k).model_dump_json()) for k in keys}
        return json.dumps(blob, sort_keys=True, separators=(",", ":"))

    @property
    def extraction_hash(self) -> str:
        """Identifies a feature table. Excludes splits/training/tracking."""
        return hashlib.sha256(
            self._stable(("data", "signal", "windowing", "features")).encode()
        ).hexdigest()[:12]

    @property
    def full_hash(self) -> str:
        """Identifies a run."""
        return hashlib.sha256(
            self._stable(
                ("data", "signal", "windowing", "features", "splits", "training")
            ).encode()
        ).hexdigest()[:12]

    @property
    def n_features_per_channel(self) -> int:
        """R17: never hardcode 14. Derived from the band table."""
        return 2 * len(self.features.bands) + 4  # bp_log + bp_rel, + 4 temporal

    def window_samples(self) -> int:
        return int(round(self.windowing.length_sec * self.signal.sample_rate))


def load(path: str | Path) -> Config:
    raw = yaml.safe_load(Path(path).read_text(encoding="utf-8")) or {}
    return Config.model_validate(raw)
